export const pathsConfig = {
  start: '/',
  register: '/signup',
  login: '/signin',
  resetPassword: '/recovery',
  platformsChoice : '/platforms-choice',
  gamesChoice: '/games-choice',
  features: '/features',
  partners: '/partners',
  contacts: '/contacts',
  terms: '/terms',
  support: '/support',
  subscription: '/subscription',
  payment: '/payment',
  feed: '/feed',
}