export const userList = [
  {
    id: 1,
    name: 'dariy-iva',
    email: 'dashann@mail.ru',
    avatar: '',
    password: '123456',
    birthday: '1992-07-10',
    subscription: 'annual',
    platforms: ['pc'],
    gamesIdList: [],
    friendsIdList: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    level: 10,
  },
  {
    id: 2,
    name: 'MirinaAkhaviik',
    email: 'mirina@ak.com',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['mobile', 'ps'],
    gamesIdList: [],
    friendsIdList: [],
    level: 54,
  },
  {
    id: 3,
    name: 'Mandalorian5917',
    email: 'mandalor@ia.fn',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['mobile', 'ps'],
    gamesIdList: [],
    friendsIdList: [],
    level: 89,
  },
  {
    id: 4,
    name: 'waaaattson',
    email: 'waatson@ia.sw',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc', 'xbox', 'mobile'],
    gamesIdList: [],
    friendsIdList: [],
    level: 89,
  },
  {
    id: 5,
    name: 'gboy6827',
    email: 'boy@mail.ru',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['mobile', 'ps'],
    gamesIdList: [],
    friendsIdList: [],
    level: 55,
  },
  {
    id: 6,
    name: 'gboy681',
    email: 'boy1@ui.en',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc', 'xbox', 'mobile'],
    gamesIdList: [],
    friendsIdList: [],
    level: 27,
  },
  {
    id: 7,
    name: 'girl90',
    email: 'gerl90@ya.ru',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: [],
    gamesIdList: ['switch'],
    friendsIdList: [],
    level: 11,
  },
  {
    id: 8,
    name: 'HungryDima',
    email: 'dima@skl.com',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['switch', 'mobile'],
    gamesIdList: [],
    friendsIdList: [],
    level: 1,
  },
  {
    id: 9,
    name: 'ivan18',
    email: 'ivanyn@main.ru',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc', 'xbox', 'mobile'],
    gamesIdList: [],
    friendsIdList: [],
    level: 60,
  },
  {
    id: 10,
    name: 'mashaCool',
    email: 'mashuny@ops.com',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['mobile', 'ps'],
    gamesIdList: [],
    friendsIdList: [],
    level: 14,
  },
  {
    id: 11,
    name: 'patanLucky',
    email: 'lucky19@ui.fn',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc', 'ps'],
    gamesIdList: [],
    friendsIdList: [],
    level: 1,
  },
  {
    id: 12,
    name: 'annaSmith',
    email: 'smith@mail.ru',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc', 'xbox', 'mobile'],
    gamesIdList: [],
    friendsIdList: [],
    level: 2,
  },
  {
    id: 13,
    name: 'pvl1001',
    email: 'pvl1001@tutu.ru',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc', 'ps'],
    gamesIdList: [],
    friendsIdList: [],
    level: 1,
  },
  {
    id: 14,
    name: 'garry',
    email: 'omen@omen.com',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['mobile'],
    gamesIdList: [],
    friendsIdList: [],
    level: 99,
  },
  {
    id: 15,
    name: 'edward',
    email: 'wrd@mail.sw',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc', 'xbox', 'mobile'],
    gamesIdList: [],
    friendsIdList: [],
    level: 17,
  },
  {
    id: 16,
    name: 'chucky',
    email: 'chucky@chucky.hv',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc'],
    gamesIdList: [],
    friendsIdList: [],
    level: 8,
  },
  {
    id: 17,
    name: 'marryPop',
    email: 'mary@nast.en',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc', 'xbox', 'mobile'],
    gamesIdList: [],
    friendsIdList: [],
    level: 98,
  },
  {
    id: 18,
    name: 'nuxt',
    email: 'nuxt@nuxt.nw',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['xbox'],
    gamesIdList: [],
    friendsIdList: [],
    level: 13,
  },
  {
    id: 19,
    name: 'ronWisley',
    email: 'ron@ron.en',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc', 'ps', 'mobile', 'xbox'],
    gamesIdList: [],
    friendsIdList: [],
    level: 19,
  },
  {
    id: 20,
    name: 'hagred',
    email: 'hagred@hagred.com',
    avatar: '',
    password: '111111',
    birthday: '',
    subscription: '',
    platforms: ['pc', 'ps'],
    gamesIdList: [],
    friendsIdList: [],
    level: 56,
  },
];